/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'moharama' at '9/1/16 4:41 PM' with Gradle 3.0
 *
 * @author moharama, @date 9/1/16 4:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
